version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: weather-timescaledb
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - weather-network

  redis:
    image: redis:7-alpine
    container_name: weather-redis
    ports:
      - "6379:6379"
    networks:
      - weather-network

  weather-app:
    build: .
    container_name: weather-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://timescaledb:5432/weatherdb
      - SPRING_DATASOURCE_USERNAME=weather_user
      - SPRING_DATASOURCE_PASSWORD=weather_pass
      - SPRING_REDIS_HOST=redis
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-aea9a11abb510253fd3f924f19ac2289}
    ports:
      - "8080:8080"
    depends_on:
      - timescaledb
      - redis
    networks:
      - weather-network

volumes:
  timescale_data:

networks:
  weather-network:
    driver: bridge