# Security & Compliance Configuration
server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: weather-service
  port: 8443
  http2:
    enabled: true
  compression:
    enabled: true
  error:
    include-stacktrace: never
    include-message: never

spring:
  security:
    require-ssl: true
  
  # Database encryption
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:weatherdb}?sslmode=require&sslcert=client-cert.pem&sslkey=client-key.pem&sslrootcert=ca-cert.pem
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  # Redis security
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    ssl: true
    timeout: 5000ms

  # Session security
  session:
    store-type: redis
    timeout: 1800s
    cookie:
      secure: true
      http-only: true
      same-site: strict
      max-age: 1800

# JWT Security
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000  # 1 hour
  refresh-expiration: 86400000  # 24 hours
  issuer: energy-analytics-platform
  audience: energy-analytics-users

# Security headers and CORS
security:
  headers:
    content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:; frame-ancestors 'none';"
    x-frame-options: DENY
    x-content-type-options: nosniff
    x-xss-protection: "1; mode=block"
    strict-transport-security: "max-age=31536000; includeSubDomains; preload"
  
  cors:
    allowed-origins: 
      - https://energyanalytics.com
      - https://app.energyanalytics.com
      - https://*.energyanalytics.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Data encryption
encryption:
  algorithm: AES/GCM/NoPadding
  key-length: 256
  secret-key: ${ENCRYPTION_SECRET_KEY}
  
# Audit logging
audit:
  enabled: true
  log-requests: true
  log-responses: false
  sensitive-headers: Authorization,Cookie,X-API-Key
  retention-days: 90

# Rate limiting (enhanced)
rate-limiting:
  enabled: true
  default-limit: 100
  window-size: 3600  # 1 hour
  redis-key-prefix: "rate_limit:"
  
# GDPR Compliance
gdpr:
  enabled: true
  data-retention-days: 2555  # 7 years
  anonymization-enabled: true
  consent-tracking: true
  right-to-be-forgotten: true

# Monitoring and alerting
monitoring:
  security-events: true
  failed-login-threshold: 5
  suspicious-activity-detection: true
  alert-webhook: ${SECURITY_ALERT_WEBHOOK}

logging:
  level:
    org.springframework.security: INFO
    com.weather.service.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"