# Test environment configuration

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  
  redis:
    host: localhost
    port: 6379
    timeout: 1000ms
  
  h2:
    console:
      enabled: true

# Disable security for tests
jwt:
  secret: test-secret-key-for-testing-only
  expiration: 3600000

# Test-specific logging
logging:
  level:
    com.weather.service: DEBUG
    org.springframework.web: WARN
    org.hibernate: WARN