server:
  port: 8080

spring:
  application:
    name: weather-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: weather_user
    password: weather_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

openweather:
  api:
    key: ${OPENWEATHER_API_KEY:aea9a11abb510253fd3f924f19ac2289}
    url: https://api.openweathermap.org/data/2.5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  secret: myVerySecretKeyForJWTTokenGeneration123456789
  expiration: 86400000

app:
  security:
    enabled: false
  data:
    initialize: true

logging:
  level:
    com.weather.service: DEBUG
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.security.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/weather-service.log